version: '3'
services:

  weewx-core:
    container_name: weewx-core
    image: weewx
    mac_address: d0:ca:ab:cd:ca:ca
    cap_add:
      - NET_ADMIN
    networks:
      pihole_pihole_network:
        ipv4_address: 192.168.X.X
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data/weewx.conf:/home/weewx/weewx.conf
      - ${PWD}/data/html/:/home/weewx/public_html/
      - ${PWD}/data/archive:/home/weewx/archive/
    restart: unless-stopped

  weewx-web:
    container_name: weewx-web
    image: nginx:alpine
    depends_on:
      - weewx-core
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data/html/:/usr/share/nginx
      - ${PWD}/src/default:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - "8080:8080"
      
networks:
  pihole_pihole_network:
    external: true
