version: '2'
networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: enp3s0 # Change your iface here (eth0 / wlan0 / etc...)
    ipam:
      config:
        - subnet: 192.168.X.X/24
          gateway: 192.168.X.X
          ip_range: 192.168.X.X/24
